"""
Property Test: Discharge Summary Completeness (Layer 1).

Property: All diagnoses, procedures, and prescriptions appear in the discharge summary.

Uses Hypothesis to generate varying numbers of diagnoses (1-10), procedures (0-5),
and verifies the discharge summary generated by EncounterService._build_discharge_summary
contains ALL of them — none are dropped.

The discharge summary is a JSONB structure containing:
- diagnoses: [{icd10_code, display_name, is_primary, is_chronic}, ...]
- procedures: [{code, description, performed_at}, ...]
- prescriptions: [] (populated by prescription module separately)
- follow_up: None (clinician fills later)

This test mocks the encounter's relationships (diagnoses, procedures) and
verifies that the generated summary is a faithful superset.

**Validates: EMR Layer 1 — Discharge Summary Data Integrity**
"""

import uuid
from datetime import datetime, timezone
from unittest.mock import MagicMock

import pytest
from hypothesis import given, settings, strategies as st

from app.modules.encounters.service import EncounterService


# ---------------------------------------------------------------------------
# Strategies: Generate synthetic clinical items
# ---------------------------------------------------------------------------
icd10_code_st = st.sampled_from([
    "E11.9", "I10", "I63.9", "I50.9", "N18.3", "J44.1", "B20",
    "A15.0", "B50.9", "D50.9", "E66.9", "F32.1", "J18.9",
])

diagnosis_name_st = st.sampled_from([
    "Type 2 Diabetes", "Hypertension", "Ischemic Stroke",
    "Heart Failure", "Chronic Kidney Disease Stage 3",
    "COPD Exacerbation", "HIV/AIDS", "Pulmonary Tuberculosis",
    "Malaria", "Iron Deficiency Anemia", "Obesity",
    "Major Depressive Disorder", "Community-Acquired Pneumonia",
])

procedure_code_st = st.sampled_from([
    "71388002", "40617009", "232717009", "18286008",
    "76164006", "44608003", "387713003",
])

procedure_desc_st = st.sampled_from([
    "Wound debridement", "Lumbar puncture", "ECG recording",
    "Blood transfusion", "Chest X-ray", "IV catheter insertion",
    "Nebulizer treatment",
])

utc_datetime_st = st.datetimes(
    min_value=datetime(2020, 1, 1), max_value=datetime(2030, 12, 31),
).map(lambda dt: dt.replace(tzinfo=timezone.utc))


def _build_mock_diagnosis(icd10_code: str, display_name: str,
                          is_primary: bool, is_chronic: bool) -> MagicMock:
    """
    Build a mock Diagnosis object simulating the SQLAlchemy model.

    Args:
        icd10_code: ICD-10 code (e.g., "E11.9").
        display_name: Human-readable diagnosis name.
        is_primary: Whether this is the primary diagnosis.
        is_chronic: Whether this is a chronic condition.

    Returns:
        MagicMock with required attributes for discharge summary generation.
    """
    mock = MagicMock()
    mock.id = uuid.uuid4()
    mock.icd10_code = icd10_code
    mock.display_name = display_name
    mock.is_primary = is_primary
    mock.is_chronic = is_chronic
    return mock


def _build_mock_procedure(code: str, description: str,
                          performed_at: datetime | None) -> MagicMock:
    """
    Build a mock Procedure object simulating the SQLAlchemy model.

    Args:
        code: SNOMED procedure code.
        description: Human-readable procedure description.
        performed_at: When the procedure was performed.

    Returns:
        MagicMock with required attributes for discharge summary generation.
    """
    mock = MagicMock()
    mock.id = uuid.uuid4()
    mock.code = code
    mock.description = description
    mock.performed_at = performed_at
    return mock


# ---------------------------------------------------------------------------
# Property Tests
# ---------------------------------------------------------------------------
@pytest.mark.property
class TestPropertyDischargeCompleteness:
    """
    Property-based tests proving discharge summary completeness.

    Core invariant: every diagnosis and procedure attached to an encounter
    appears in the generated discharge summary — none are silently dropped.
    """

    @given(data=st.data())
    @settings(max_examples=50, deadline=None)
    @pytest.mark.asyncio
    async def test_property_all_diagnoses_present_in_summary(self, data):
        """
        Property: For any set of 1-10 diagnoses attached to an encounter,
        ALL appear in the discharge summary's diagnoses list with correct
        icd10_code, display_name, is_primary, and is_chronic fields.
        """
        # Generate 1-10 diagnoses
        num_diagnoses = data.draw(st.integers(min_value=1, max_value=10))
        diagnoses = []
        for i in range(num_diagnoses):
            dx = _build_mock_diagnosis(
                icd10_code=data.draw(icd10_code_st),
                display_name=data.draw(diagnosis_name_st),
                is_primary=(i == 0),  # First is primary
                is_chronic=data.draw(st.booleans()),
            )
            diagnoses.append(dx)

        # Build mock encounter with diagnoses and empty procedures
        mock_encounter = MagicMock()
        mock_encounter.diagnoses = diagnoses
        mock_encounter.procedures = []

        # Generate discharge summary
        service = EncounterService()
        summary = service._build_discharge_summary(mock_encounter)

        # INVARIANT: All diagnoses appear in the summary
        assert len(summary["diagnoses"]) == num_diagnoses, (
            f"Expected {num_diagnoses} diagnoses in summary, "
            f"got {len(summary['diagnoses'])}"
        )

        # Verify each diagnosis is faithfully represented
        for i, dx in enumerate(diagnoses):
            entry = summary["diagnoses"][i]
            assert entry["icd10_code"] == dx.icd10_code, (
                f"Diagnosis {i}: expected code '{dx.icd10_code}', "
                f"got '{entry['icd10_code']}'"
            )
            assert entry["display_name"] == dx.display_name, (
                f"Diagnosis {i}: expected name '{dx.display_name}', "
                f"got '{entry['display_name']}'"
            )
            assert entry["is_primary"] == dx.is_primary
            assert entry["is_chronic"] == dx.is_chronic

    @given(data=st.data())
    @settings(max_examples=50, deadline=None)
    @pytest.mark.asyncio
    async def test_property_all_procedures_present_in_summary(self, data):
        """
        Property: For any set of 0-5 procedures attached to an encounter,
        ALL appear in the discharge summary's procedures list with correct
        code, description, and performed_at fields.
        """
        # Generate 0-5 procedures
        num_procedures = data.draw(st.integers(min_value=0, max_value=5))
        procedures = []
        for _ in range(num_procedures):
            proc = _build_mock_procedure(
                code=data.draw(procedure_code_st),
                description=data.draw(procedure_desc_st),
                performed_at=data.draw(
                    st.one_of(st.none(), utc_datetime_st)
                ),
            )
            procedures.append(proc)

        # Build mock encounter with procedures and a single diagnosis
        mock_encounter = MagicMock()
        mock_encounter.diagnoses = [
            _build_mock_diagnosis("I10", "Hypertension", True, True)
        ]
        mock_encounter.procedures = procedures

        # Generate discharge summary
        service = EncounterService()
        summary = service._build_discharge_summary(mock_encounter)

        # INVARIANT: All procedures appear in the summary
        assert len(summary["procedures"]) == num_procedures, (
            f"Expected {num_procedures} procedures in summary, "
            f"got {len(summary['procedures'])}"
        )

        # Verify each procedure is faithfully represented
        for i, proc in enumerate(procedures):
            entry = summary["procedures"][i]
            assert entry["code"] == proc.code, (
                f"Procedure {i}: expected code '{proc.code}', "
                f"got '{entry['code']}'"
            )
            assert entry["description"] == proc.description, (
                f"Procedure {i}: expected desc '{proc.description}', "
                f"got '{entry['description']}'"
            )
            # performed_at is ISO formatted or None
            if proc.performed_at is not None:
                assert entry["performed_at"] == proc.performed_at.isoformat()
            else:
                assert entry["performed_at"] is None

    @given(data=st.data())
    @settings(max_examples=50, deadline=None)
    @pytest.mark.asyncio
    async def test_property_combined_completeness(self, data):
        """
        Property: For any combination of 1-10 diagnoses and 0-5 procedures,
        the discharge summary contains ALL items from both collections.

        This tests the combined case to ensure no interaction effects cause
        data loss when both collections are non-empty.
        """
        # Generate varying numbers
        num_dx = data.draw(st.integers(min_value=1, max_value=10))
        num_proc = data.draw(st.integers(min_value=0, max_value=5))

        diagnoses = [
            _build_mock_diagnosis(
                icd10_code=data.draw(icd10_code_st),
                display_name=data.draw(diagnosis_name_st),
                is_primary=(i == 0),
                is_chronic=data.draw(st.booleans()),
            )
            for i in range(num_dx)
        ]

        procedures = [
            _build_mock_procedure(
                code=data.draw(procedure_code_st),
                description=data.draw(procedure_desc_st),
                performed_at=data.draw(st.one_of(st.none(), utc_datetime_st)),
            )
            for _ in range(num_proc)
        ]

        mock_encounter = MagicMock()
        mock_encounter.diagnoses = diagnoses
        mock_encounter.procedures = procedures

        service = EncounterService()
        summary = service._build_discharge_summary(mock_encounter)

        # INVARIANT: counts match exactly (no items dropped or duplicated)
        assert len(summary["diagnoses"]) == num_dx
        assert len(summary["procedures"]) == num_proc

        # INVARIANT: all ICD-10 codes present in summary
        summary_codes = {d["icd10_code"] for d in summary["diagnoses"]}
        input_codes = {dx.icd10_code for dx in diagnoses}
        assert input_codes.issubset(summary_codes), (
            f"Missing diagnosis codes: {input_codes - summary_codes}"
        )

        # INVARIANT: all procedure codes present in summary
        summary_proc_codes = {p["code"] for p in summary["procedures"]}
        input_proc_codes = {p.code for p in procedures}
        assert input_proc_codes.issubset(summary_proc_codes), (
            f"Missing procedure codes: {input_proc_codes - summary_proc_codes}"
        )
